server {
    listen 443 ssl;
    http2 on;

    server_name graphdash.graphcert.cede-apps.ch;

    ssl_certificate     /etc/letsencrypt/live/graphcert.cede-apps.ch/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/graphcert.cede-apps.ch/privkey.pem;

    proxy_set_header Host              $host;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Real-IP         $remote_addr;

    location / {proxy_pass http://dashy:8080/;}

    location = /grafana    {return 301 /grafana/;}
    location = /prometheus {return 301 /prometheus/;}

    location /grafana/    {proxy_pass http://grafana:3000;}
    location /prometheus/ {proxy_pass http://prometheus:9090;}
}

server {
    listen 9443 ssl;
    http2 on;

    server_name graphdash.graphcert.cede-apps.ch;

    ssl_certificate     /etc/letsencrypt/live/graphcert.cede-apps.ch/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/graphcert.cede-apps.ch/privkey.pem;

    location / {
        proxy_pass http://infisical:8080;

        proxy_http_version 1.1;
        proxy_set_header Host              $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        "upgrade";
    }
}